### ISSUE TITLE
Proposal: Release the use of 10.127.0.0/24

### ISSUE THREAD

**Issue by NeoChen1024** [NeoCloud/NeoNetwork#142]
Since last year, legacy tunnels have been phased out. Thus, there's no reason anymore to reserve the usage 10.127.0.0/24.

**Comment by isjerryxiao** [comment]
Yeah, maybe we should repurpose 10.127.0.0/24 for anycast? 10.127.255.54 is really not a nice-looking address.

**Comment by NeoChen1024** [comment]
> Yeah, maybe we should repurpose 10.127.0.0/24 for anycast? 10.127.255.54 is really not a nice-looking address.

Right, I think it's reasonable to release this network for anycast addresses
