### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by keatonaglair** [NeoCloud/NeoNetwork#147]
I've been waiting nearing on 2 weeks for my pull requests to be pushed.
Is anyone still maintaining this?

**Comment by keatonaglair** [comment]
Why did you close my pull requests?

**Comment by septs** [comment]
Please follow the minimum principle.

e.g: /30

**Comment by keatonaglair** [comment]
I'm sorry? I run 44.135.136.0/21 among other space and am near full. I only have a /24 of public so far but I have several ARIN waitlist tickets in the works. 10.127.160.0/20, like much of my space will be 1:1 NAT'd to my internal IPs. I need more than a /30.

**Comment by keatonaglair** [comment]
Can you re open this issue?
