### ISSUE TITLE
IPv6 proposal

### ISSUE THREAD

**Issue by santost12** [NeoCloud/NeoNetwork#26]
Proposed IPv6 network space:  **fd10:127:a218::/48** or **fd10:127::/32**

Each person can allocate a /64 or /48 depending on which one is used. The /48 helps avoid conflicts with other networks but the /32 looks nicer and closer to 10.127.x.x for IPv4.

**Comment by NeoChen1024** [comment]
What about fd10:5f37:59df::/48 ?

**Comment by NeoChen1024** [comment]
I think fd10:127::/32 is good

**Comment by santost12** [comment]
I'm closing this issue because I was able to add my route6 object.
